[2023-06-16T21:46:02.867+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:46:02.891+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [queued]>
[2023-06-16T21:46:02.891+0000] {taskinstance.py:1308} INFO - Starting attempt 19 of 22
[2023-06-16T21:46:02.940+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): executor_task> on 2019-06-01 16:00:00+00:00
[2023-06-16T21:46:02.951+0000] {standard_task_runner.py:57} INFO - Started process 207 to run task
[2023-06-16T21:46:02.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'executor_task', 'manual__2019-06-01T16:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag.py', '--cfg-path', '/tmp/tmpkwdr8alu']
[2023-06-16T21:46:02.960+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask executor_task
[2023-06-16T21:46:03.057+0000] {task_command.py:410} INFO - Running <TaskInstance: demo_dag.executor_task manual__2019-06-01T16:00:00+00:00 [running]> on host 6a4a685f908e
[2023-06-16T21:46:03.156+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-16T21:46:03.256+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='personaltraingcp@gmail.com' AIRFLOW_CTX_DAG_OWNER='Leyner_Bejarano' AIRFLOW_CTX_DAG_ID='demo_dag' AIRFLOW_CTX_TASK_ID='executor_task' AIRFLOW_CTX_EXECUTION_DATE='2019-06-01T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='manual__2019-06-01T16:00:00+00:00'
[2023-06-16T21:46:03.259+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T21:46:03.260+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \n        cd /opt/***/dags/scripts &&\n        python lambdaExecutor.py -dt 2019-06-01 -dh 16 -q https://sqs.us-east-2.amazonaws.com/147929168898/lokaInterviewSQS -ak AKIASE4KD7QBGVHE4G7U -sk AKIASE4KD7QBGVHE4G7U\n        ']
[2023-06-16T21:46:03.314+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T21:46:04.858+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-16T21:46:04.894+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-16T21:46:04.907+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag, task_id=executor_task, execution_date=20190601T160000, start_date=20230616T214602, end_date=20230616T214604
[2023-06-16T21:46:04.956+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 101 for task executor_task (Bash command failed. The command returned a non-zero exit code 1.; 207)
[2023-06-16T21:46:04.996+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T21:46:05.093+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
